export const stories = [
  {
    path: '/sounds/1.mp3',
    name: 'Spinnentanz',
    beschreibung: 'Eine Geschichte von 7 Spinnen, die einen Tanz tanzen und singen.'
  },
  {
    path: '/sounds/2.mp3',
    name: 'Perlenschatz',
    beschreibung: 'Eine Geschichte von einem Perlenkönig, der seinen Schatz sucht.'
  },
  {
    path: '/sounds/3.mp3',
    name: 'Kleines Mädchen',
    beschreibung: 'Eine Geschichte von einem kleinen Mädchen, das in einem Korb sitzt und häkelt.'
  },
  {
    path: '/sounds/4.mp3',
    name: "Fingerring verloren",
    beschreibung: 'Eine Geschichte von einem Zwerg, der einen Fingerring verliert und ihn wieder findet.'
  },
  {
    path: '/sounds/5.mp3',
    name: 'Königin der Nacht',
    beschreibung: 'Eine Geschichte von einer Königin, die Party feiert und mit ihren Gästen Poker spielt.'
  },
  {
    path: '/sounds/6.mp3',
    name: 'Zauberwald',
    beschreibung: 'Eine Geschichte von einem magischen Wald, wo die Bäume Geschichten erzählen und die Blumen singen.'
  },
  {
    path: '/sounds/7.mp3',
    name: 'Mondscheindrache',
    beschreibung: 'Eine Geschichte von einem kleinen Drachen, der nachts im Mondschein tanzt und Sterne sammelt.'
  },
  {
    path: '/sounds/8.mp3',
    name: 'Regenbogenfisch',
    beschreibung: 'Eine Geschichte von einem bunten Fisch, der in einer Unterwasserstadt Musik macht und andere Fische zum Lachen bringt.'
  },
  {
    path: '/sounds/final.mp3',
    name: 'Konklusion',
    beschreibung: 'Eine Geschichte, die alles zusammenfasst und ein Ende macht.'
  }
];

export const scores = [
  {
    path: '/sounds/1/1a.mp3',
    name: '1a',
    number: 1,
    type: 'answer',
    letter: 'a',
    addictionScore: 0,
    awarenessScore: 3,
    id: 1,
  },
  {
    path: '/sounds/1/1b.mp3',
    name: '1b',
    number: 1,
    type: 'answer',
    letter: 'b',
    addictionScore: 2,
    awarenessScore: 1,
    id: 2,

  },
  {
    path: '/sounds/1/1q.mp3',
    name: '1q',
    number: 1,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 3,
  },
  {
    path: '/sounds/2/2a.mp3',
    name: '2a',
    number: 2,
    type: 'answer',
    letter: 'a',
    addictionScore: 0,
    awarenessScore: 3,
    id: 4,
  },
  {
    path: '/sounds/2/2b.mp3',
    name: '2b',
    number: 2,
    type: 'answer',
    letter: 'b',
    addictionScore: 0,
    awarenessScore: 3,
    id: 5,
  },
  {
    path: '/sounds/2/2q.mp3',
    name: '2q',
    number: 2,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 6,
  },
  {
    path: '/sounds/3/3a.mp3',
    name: '3a',
    number: 3,
    type: 'answer',
    letter: 'a',
    addictionScore: 0,
    awarenessScore: 3,
    id: 7,
  },
  {
    path: '/sounds/3/3b.mp3',
    name: '3b',
    number: 3,
    type: 'answer',
    letter: 'b',
    addictionScore: 0,
    awarenessScore: 3,
    id: 8,
  },
  {
    path: '/sounds/3/3q.mp3',
    name: '3q',
    number: 3,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 9,
  },
  {
    path: '/sounds/4/4a.mp3',
    name: '4a',
    number: 4,
    type: 'answer',
    letter: 'a',

    id: 10,
  },
  {
    path: '/sounds/4/4b.mp3',
    name: '4b',
    number: 4,
    type: 'answer',
    letter: 'b',
    addictionScore: 0,
    awarenessScore: 3,
    id: 11,
  },
  {
    path: '/sounds/4/4q.mp3',
    name: '4q',
    number: 4,
    type: 'question',
    letter: 'q',
    addictionScoreA: 0,
    awarenessScoreA: 3,
    addictionScoreB: 0,
    awarenessScoreB: 3,
    id: 12,
  }
]

export const questions = [
  {
    path: '/sounds/q1.mp3',
    name: '1q',
    number: 1,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 1,
    answer: null
  },
  {
    path: '/sounds/q2.mp3',
    name: '2q',
    number: 2,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 2,
    answer: null
  },
  {
    path: '/sounds/q3.mp3',
    name: '3q',
    number: 3,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 3,
    answer: null
  },
  {
    path: '/sounds/q4.mp3',
    name: '4q',
    number: 4,
    type: 'question',
    letter: 'q',
    addictionScoreA: 0,
    awarenessScoreA: 3,
    addictionScoreB: 0,
    awarenessScoreB: 3,
    id: 4,
    answer: null
  },
  {
    path: '/sounds/q5.mp3',
    name: '5q',
    number: 5,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 5,
    answer: null
  },
  {
    path: '/sounds/q6.mp3',
    name: '6q',
    number: 6,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 6,
    answer: null
  },
  {
    path: '/sounds/q7.mp3',
    name: '7q',
    number: 7,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 7,
    answer: null
  },
  {
    path: '/sounds/q8.mp3',
    name: '8q',
    number: 8,
    type: 'question',
    letter: 'q',
    addictionScoreA: 0,
    awarenessScoreA: 3,
    addictionScoreB: 0,
    awarenessScoreB: 3,
    id: 8,
    answer: null
  },
  {
    path: '/sounds/q9.mp3',
    name: '9q',
    number: 9,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 9,
    answer: null
  },
  {
    path: '/sounds/q10.mp3',
    name: '10q',
    number: 10,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 10,
    answer: null
  },
  {
    path: '/sounds/q11.mp3',
    name: '11q',
    number: 11,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 11,
    answer: null
  },
  {
    path: '/sounds/q12.mp3',
    name: '12q',
    number: 12,
    type: 'question',
    letter: 'q',
    addictionScoreA: 0,
    awarenessScoreA: 3,
    addictionScoreB: 0,
    awarenessScoreB: 3,
    id: 12,
    answer: null
  },
  {
    path: '/sounds/q13.mp3',
    name: '13q',
    number: 13,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 13,
    answer: null
  },
  {
    path: '/sounds/q14.mp3',
    name: '14q',
    number: 14,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 14,
    answer: null
  },
  {
    path: '/sounds/q15.mp3',
    name: '15q',
    number: 15,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 15,
    answer: null
  },
  {
    path: '/sounds/q16.mp3',
    name: '16q',
    number: 16,
    type: 'question',
    letter: 'q',
    addictionScoreA: 0,
    awarenessScoreA: 3,
    addictionScoreB: 0,
    awarenessScoreB: 3,
    id: 16,
    answer: null
  },
  {
    path: '/sounds/q17.mp3',
    name: '17q',
    number: 17,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 17,
    answer: null
  },
  {
    path: '/sounds/q18.mp3',
    name: '18q',
    number: 18,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 18,
    answer: null
  },
  {
    path: '/sounds/q19.mp3',
    name: '19q',
    number: 19,
    type: 'question',
    letter: 'q',
    addictionScoreA: 1,
    awarenessScoreA: 2,
    addictionScoreB: 2,
    awarenessScoreB: 1,
    id: 19,
    answer: null
  },
  {
    path: '/sounds/q20.mp3',
    name: '20q',
    number: 20,
    type: 'question',
    letter: 'q',
    addictionScoreA: 0,
    awarenessScoreA: 3,
    addictionScoreB: 0,
    awarenessScoreB: 3,
    id: 20,
    answer: null
  }
]